### PR TITLE
updated test and fixed part of #23

### PR DESCRIPTION
**Pull request by BenjaminSchubert**
I completely rewrote the tests in a pythonic way. Now running
these tests is as easy as python -m unittest discover in test/

I'm planning to add more tests and especially unittest for
command line parsing which has several issues (-mllvm flags)
for instance.

The only test I did not move is :

`mystery:
	otool -X -s __LLVM __llvm_bc main > main.otool
	xxd -r  main.otool
	xxd -r  main.otool main.xxd`

as I could not understand what it does and could not find otool
on my ubuntu system. (any help there ?)

The fix for as is because it is not in the top-level directory.

I would be of the opinion of moving it to the top level directory. What would you think @travitch ?

I also know that this pull request is quite a big change, so if you would prefer not integrate it, I can also just create a patch for the #23 and resubmit it.

### CODE REVIEW

**Comment by ianamason** [comment]
otool is the mac version of objdump.

the mystery is the behavior of xxd which forced me to eliminate
its use, and write my own. so you can ignore it safely.

**Comment by travitch** [comment]
@BenjaminSchubert Excellent, thanks.  I want to merge this - just let me play with it a bit

**Comment by ianamason** [comment]
On a related note I added support for travis ci into my fork. currently it builds apache on linux
with clang, and a similar build for dragonegg is there but commented out while broken.

Are you interested in this too @travitch?  

Two pulls are better than one?

**Comment by travitch** [comment]
Sure, I'd love to have that.  Whatever is easiest for you works for me.

**Pull request merged**
