### PR TITLE
Support for storing bitcode versions of object files in a separate tree.

### PR DESCRIPTION
**Pull request by kalibera**
Hi Travis,

I've started using your scripts for GNU-R, but I had to add a new feature. The GNU-R built system builds some R packages in temporary directories, where also the object files are placed, and the original wllvm places there also the bitcode files. However, these temporary directories are deleted during the build, so extract-bc won't work. The fact that some building happens into temporary directories is buried well within GNU-R itself (R has API for installing packages, the install runs within GNU-R instance). So, my modification allows storing the bitcode files in a specific directory. Feel free to include/adapt this into your version, perhaps it could be useful with other projects as well. I have not tested my modification on Windows (and it is certainly not robust against the same directory trees on different drives, possibly it won't work with mounted drives). Also, the coding is slightly simple, I don't program in Python. 

Best
Tomas

### CODE REVIEW

**Comment by kalibera** [comment]
Sorry, there is a race condition in the fix (won't work in parallel builds).

**Comment by ianamason** [comment]
Have you tried just building in an environment where rm is aliased to a no-op?

**Comment by travitch** [comment]
Are you sure you need this?  The idea of wllvm was to be robust against this sort of build system by inserting the bitcode into generated object files.  That way, no matter where the object files are moved to or linked into (executables or libraries), the bitcode always follows them around.

The bitcode files on disk only matter very briefly: between the time that the compiler generates an assembly file and the time it calls the assembler.  After that, the bitcode has been inserted into the object file.

I did need this once (and I think it used to be supported) in the case where too much bitcode was generated during a build to fit in an ELF section.  That seems like an uncommon problem, though.

**Comment by ianamason** [comment]
I thought we just embedded the paths to the bitcode in the object files.

**Comment by travitch** [comment]
Ah, right you are... it has been a long time since I was actively using this.

**Comment by ianamason** [comment]
I still agree with you @travitch, I would prefer to trick an ugly build system than adapt to it
unnecessarily. We don't want to get involved in a race to the bottom.  In the days of yore
we side stepped things like this preventing the delete from happening.

**Comment by delcypher** [comment]
On 27 May 2015 3:27 pm, "Tristan Ravitch" <notifications@github.com> wrote:
>
> Are you sure you need this? The idea of wllvm was to be robust against
this sort of build system by inserting the bitcode into generated object
files. That way, no matter where the object files are moved to or linked
into (executables or libraries), the bitcode always follows them around.
>
> The bitcode files on disk only matter very briefly: between the time that
the compiler generates an assembly file and the time it calls the
assembler. After that, the bitcode has been inserted into the object file.

Eh? Last time I read the code IIRC the bitcode files were **not** put into
object files. Instead paths to the bitcode files on disk were put into
object files headers.

**Comment by travitch** [comment]
@delcypher Yeah, I was wrong on that point.  The first version of the scripts put the actual bitcode into object files.

**Comment by kalibera** [comment]
This cannot be easily tricked on the R side. The problem is with installing/building R packages. This is done from a running instance of R using an R function call "install.packages". An R user can install a package at any time (from a running instance of R), not just when building R. The implementation of install.packages uses the R per-session temporary directory for compilation of C source code of the packages (the support for R per-session temporary directories is then again more general, used by many different parts of R). And the R per-session temporary directory is indeed deleted when the R session ends. 

So, when building R, a number of source files are built normally in place given by autotools logic and do not cause trouble with wllvm. But, some packages that are part of the distribution have to be installed, this installation runs in R sessions... and there is the problem. I don't think this scenario would be fundamentally broken and I think it can be easily present in other language runtimes that allow extensions in C.

I've been using LTO and -also-emit-llvm option of the gold linker plugin before, but they removed the option from LLVM in 3.6... I am not sure what was the intention for wllvm, but for me it is a nice tool to encapsulate the pain of getting the bitcode for binaries, so that we don't have to modify complicated systems every time LLVM changes (which is not terribly infrequent). And to a level to simplify all the hacking around and configuring (building LLVM from source to get gold, building binutils to support gold with plugins, writing wrapper scripts for some tools for binutils, twiddling with environment variables to fool the configure script of R, etc). So for me it seems natural to have the support for temporary build directories in wllvm.

**Comment by ianamason** [comment]
In order to keep our users happy @kalibera  we have added a feature with this functionality
to the SRI fork. It will eventually end up here, but will be in the 1.0.19 version of the pip package before that.

**Comment by kalibera** [comment]
Thanks. In the meantime we hacked this on the R side, so the feature is no longer needed for R. But perhaps it could be useful to others at some point.

**Pull request closed without merging**
