### PR TITLE
Update tutorial

### PR DESCRIPTION
**Pull request by bchurchill**
The old tutorial is dated; this updates it for Ubuntu 16.04, clang-3.8 and current apache.  It also adds instructions for building a complete binary from the bitcode in case anyone is interested in this.  The old tutorial is left behind for anyone who wants to use 14.04; this just adds a new file.

### CODE REVIEW

**Comment by ianamason** [comment]
Since I wrote the tutorial, I will respond.  I'm happy to have a tutorial_ubuntu-XXX, but 
it would be more interesting to have a slightly more advanced tutorial that doesn't cover the
same material with 4 replaced by 6, not trying to trivialize here.  

Could I interest you in that? One possibility would be to not only build apache, but also its dependency libraries like  apr apr_util and pcre. then should how you can  llvm-link then
and create a static binary.

Just an idea.

**Comment by ianamason** [comment]
Gift horses should not have mouth exams.

**Comment by bchurchill** [comment]
Heh, sorry I didn't respond earlier.  Perhaps the one nontrivial change was
that the link to download Apache was broken.

**Comment by ianamason** [comment]
Thanks, yes that is the number one reason our travis builds used to fail.
I fixed it in the yml but perhaps not in the tutorial.

**Pull request merged**
